version: '3.8'
services:
  dockermon:
    container_name: dockermon
    image: webfreakeric/dockermon-monitor:latest
    command: /bin/bash /app/dockermon-app/start.sh
    restart: always
    env_file: ./.env
    deploy:
      labels:
        com.docker.compose.project: 'dockermon'
    environment:
      DOCKERMON_BACKEND_WS_PORT: $DOCKERMON_BACKEND_WS_PORT
      DOCKERMON_BACKEND_API_PORT: $DOCKERMON_BACKEND_API_PORT
      DOCKERMON_FRONTEND_PORT: $DOCKERMON_FRONTEND_PORT
      DOCKERMON_WORKER_HOST_ADDRESS: $DOCKERMON_WORKER_HOST_ADDRESS
      DOCKERMON_HOST_LAUNCHER_PORT: $DOCKERMON_HOST_LAUNCHER_PORT
      DOCKERMON_ENABLE_GIT_UPDATE:  $DOCKERMON_ENABLE_GIT_UPDATE
      DOCKERMON_ENABLE_GIT_BRANCH:  $DOCKERMON_ENABLE_GIT_BRANCH
      MYSQL_ROOT_PASSWORD: $MYSQL_DEV_PW
      MYSQL_DATABASE: $MYSQL_DEV_DB
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: America/New_York
    ports:
      - $DOCKERMON_FRONTEND_PORT:3800
      - $DOCKERMON_BACKEND_API_PORT:$DOCKERMON_BACKEND_API_PORT
      - $DOCKERMON_BACKEND_WS_PORT:$DOCKERMON_BACKEND_WS_PORT
    volumes:
      # - dockermon_db-config:/etc/mysql
      - dockermon_db-data:/var/lib/mysql
      - dockermon_node_modules_fe:/app/dockermon-app/frontend/node_modules
      - dockermon_node_modules_be:/app/dockermon-app/backend/node_modules
      # - ./db/backup/files/:/data_backup/data
    logging:
      driver: $DOCKERMON_LOGGING
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

volumes:
  dockermon_db-data:
  dockermon_node_modules_fe:
  dockermon_node_modules_be:
